alter table KASSA_STATIONS add constraint FK_KASSA_STATIONS_ON_ROUTES foreign key (ROUTES_ID) references KASSA_ROUTE(ID);
create unique index IDX_KASSA_STATIONS_UNIQ_STATION_NAME on KASSA_STATIONS (STATION_NAME);
create index IDX_KASSA_STATIONS_ON_ROUTES on KASSA_STATIONS (ROUTES_ID);
