alter table KASSA_TRAVEL add constraint FK_KASSA_TRAVEL_ON_TRAVEL_PASSENGER foreign key (TRAVEL_PASSENGER_ID) references KASSA_PASSANGER(ID);
create index IDX_KASSA_TRAVEL_ON_TRAVEL_PASSENGER on KASSA_TRAVEL (TRAVEL_PASSENGER_ID);
