alter table KASSA_TICKET add constraint FK_KASSA_TICKET_ON_DEPARTURE foreign key (DEPARTURE_ID) references KASSA_STATIONS(ID);
alter table KASSA_TICKET add constraint FK_KASSA_TICKET_ON_ARRIVAL foreign key (ARRIVAL_ID) references KASSA_STATIONS(ID);
alter table KASSA_TICKET add constraint FK_KASSA_TICKET_ON_TIKETS_PASSENGER foreign key (TIKETS_PASSENGER_ID) references KASSA_PASSANGER(ID);
alter table KASSA_TICKET add constraint FK_KASSA_TICKET_ON_TIKET_TRAVELS foreign key (TIKET_TRAVELS_ID) references KASSA_TRAVEL(ID);
create unique index IDX_KASSA_TICKET_UNIQ_TICKET_NUMBER on KASSA_TICKET (TICKET_NUMBER);
create index IDX_KASSA_TICKET_ON_DEPARTURE on KASSA_TICKET (DEPARTURE_ID);
create index IDX_KASSA_TICKET_ON_ARRIVAL on KASSA_TICKET (ARRIVAL_ID);
create index IDX_KASSA_TICKET_ON_TIKETS_PASSENGER on KASSA_TICKET (TIKETS_PASSENGER_ID);
create index IDX_KASSA_TICKET_ON_TIKET_TRAVELS on KASSA_TICKET (TIKET_TRAVELS_ID);
