-- begin KASSA_ROUTE
create unique index IDX_KASSA_ROUTE_UNIQ_NUMBER_ on KASSA_ROUTE (NUMBER_)^
-- end KASSA_ROUTE
-- begin KASSA_STATIONS
create unique index IDX_KASSA_STATIONS_UNIQ_STATION_NAME on KASSA_STATIONS (STATION_NAME)^
-- end KASSA_STATIONS
-- begin KASSA_TICKET
alter table KASSA_TICKET add constraint FK_KASSA_TICKET_ON_DEPARTURE foreign key (DEPARTURE_ID) references KASSA_STATIONS(ID)^
alter table KASSA_TICKET add constraint FK_KASSA_TICKET_ON_ARRIVAL foreign key (ARRIVAL_ID) references KASSA_STATIONS(ID)^
alter table KASSA_TICKET add constraint FK_KASSA_TICKET_ON_TIKETS_PASSENGER foreign key (TIKETS_PASSENGER_ID) references KASSA_PASSANGER(ID)^
alter table KASSA_TICKET add constraint FK_KASSA_TICKET_ON_TIKET_TRAVELS foreign key (TIKET_TRAVELS_ID) references KASSA_TRAVEL(ID)^
create unique index IDX_KASSA_TICKET_UNIQ_TICKET_NUMBER on KASSA_TICKET (TICKET_NUMBER)^
create index IDX_KASSA_TICKET_ON_DEPARTURE on KASSA_TICKET (DEPARTURE_ID)^
create index IDX_KASSA_TICKET_ON_ARRIVAL on KASSA_TICKET (ARRIVAL_ID)^
create index IDX_KASSA_TICKET_ON_TIKETS_PASSENGER on KASSA_TICKET (TIKETS_PASSENGER_ID)^
create index IDX_KASSA_TICKET_ON_TIKET_TRAVELS on KASSA_TICKET (TIKET_TRAVELS_ID)^
-- end KASSA_TICKET
-- begin KASSA_TRAVEL
alter table KASSA_TRAVEL add constraint FK_KASSA_TRAVEL_ON_TRAVEL_PASSENGER foreign key (TRAVEL_PASSENGER_ID) references KASSA_PASSANGER(ID)^
create index IDX_KASSA_TRAVEL_ON_TRAVEL_PASSENGER on KASSA_TRAVEL (TRAVEL_PASSENGER_ID)^
-- end KASSA_TRAVEL
-- begin KASSA_ROUTE_STATION_LINK
alter table KASSA_ROUTE_STATION_LINK add constraint FK_ROUSTA_ON_STATION foreign key (STATION_ID) references KASSA_STATIONS(ID)^
alter table KASSA_ROUTE_STATION_LINK add constraint FK_ROUSTA_ON_ROUTE foreign key (ROUTE_ID) references KASSA_ROUTE(ID)^
-- end KASSA_ROUTE_STATION_LINK
